# Any (key: value) pair in this file will be available in the DAGs as a Jinja variable.
# For e.g., if you have a key 'my_key' with value 'my_value', you can access
# it in a DAG as {{ params.my_key }}.

# Example:
# my_key: my_value

WOP_STAGE: prod

email_recipients: ["team@example.com"]
